// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDK.Data;

#nullable disable

namespace SDK.Data.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260614132733_AddExpSystem")]
    partial class AddExpSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SDK.Core.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("SDK.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GymLeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GymLeaderId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("SDK.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("SDK.Core.Entities.EncounterZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiomeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpawnRate")
                        .HasColumnType("REAL");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("EncounterZones");
                });

            modelBuilder.Entity("SDK.Core.Entities.FakemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpecialAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpecialDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EggGroup1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EggGroup2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartsManifest")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("fakemon_species", (string)null);
                });

            modelBuilder.Entity("SDK.Core.Entities.Learnset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearnLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("SpeciesId", "Generation");

                    b.ToTable("Learnsets");
                });

            modelBuilder.Entity("SDK.Core.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Generation");

                    b.HasIndex("TypeId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("SDK.Core.Entities.PokemonBaseStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PokemonBaseStats");
                });

            modelBuilder.Entity("SDK.Core.Entities.PokemonForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PokemonForms");
                });

            modelBuilder.Entity("SDK.Core.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseExpYield")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(64);

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginRegion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("PokemonSpecies");
                });

            modelBuilder.Entity("SDK.Core.Entities.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("PokemonTypes");
                });

            modelBuilder.Entity("SDK.Core.Entities.SpriteAtlasEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AtlasPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetKey")
                        .IsUnique();

                    b.ToTable("sprite_atlas_entries", (string)null);
                });

            modelBuilder.Entity("SDK.Core.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("SDK.Core.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "Locale", "Field")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SDK.Core.Entities.TypeEffectiveness", b =>
                {
                    b.Property<int>("AttackerTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenderTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DamageFactor")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("AttackerTypeId", "DefenderTypeId", "Generation");

                    b.ToTable("TypeEffectiveness");
                });

            modelBuilder.Entity("SDK.Core.Entities.VillainGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("villain_groups", (string)null);
                });

            modelBuilder.Entity("SDK.Core.Entities.VillainMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VillainGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("VillainGroupId");

                    b.ToTable("villain_members", (string)null);
                });

            modelBuilder.Entity("SDK.Core.Entities.Badge", b =>
                {
                    b.HasOne("SDK.Core.Entities.Trainer", "GymLeader")
                        .WithMany("Badges")
                        .HasForeignKey("GymLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymLeader");
                });

            modelBuilder.Entity("SDK.Core.Entities.EncounterZone", b =>
                {
                    b.HasOne("SDK.Core.Entities.PokemonSpecies", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SDK.Core.Entities.FakemonSpecies", b =>
                {
                    b.HasOne("SDK.Core.Entities.PokemonType", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDK.Core.Entities.PokemonType", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });

            modelBuilder.Entity("SDK.Core.Entities.Learnset", b =>
                {
                    b.HasOne("SDK.Core.Entities.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDK.Core.Entities.PokemonSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("SDK.Core.Entities.Move", b =>
                {
                    b.HasOne("SDK.Core.Entities.PokemonType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SDK.Core.Entities.VillainMember", b =>
                {
                    b.HasOne("SDK.Core.Entities.Character", "Character")
                        .WithMany("VillainMemberships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDK.Core.Entities.VillainGroup", "VillainGroup")
                        .WithMany("Members")
                        .HasForeignKey("VillainGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("VillainGroup");
                });

            modelBuilder.Entity("SDK.Core.Entities.Character", b =>
                {
                    b.Navigation("VillainMemberships");
                });

            modelBuilder.Entity("SDK.Core.Entities.Trainer", b =>
                {
                    b.Navigation("Badges");
                });

            modelBuilder.Entity("SDK.Core.Entities.VillainGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
