<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PokeForge.SDK.Core</PackageId>
    <Version>0.1.0</Version>
    <Description>Modèles domaine, interfaces et value objects pour PokemonSDK. Zéro dépendance NuGet externe — couche fondation du fan-game engine.</Description>
    <PackageTags>pokemon;fan-game;game-engine;rpg;dotnet;sdk</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

</Project>
